### ISSUE TITLE
Building for Windows 10 

### ISSUE THREAD

**Issue by symdeb** [mingw-deb/jack#1]
1. Windows 10 with MSYS64
2. Under MSYS/MingW installed python3
3. Below result:

$ python waf configure
Setting top to                           : D:/Test/jack-master
Setting out to                           : D:/Test/jack-master/build
Checking for 'msvc' (C++ compiler)       : C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64/CL.exe
Checking for 'msvc' (C compiler)         : C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64/CL.exe
Checking for program 'doxygen'           : not found
Checking for program 'pkg-config'        : C:\msys64\mingw64\bin/pkg-config.exe
Checking for 'alsa' >= 1.0.18            : not found
Checking for 'libffado' >= 1.999.17      : not found
Checking for 'libfreebob' >= 1.0.0       : not found
Checking for 'gtkIOStream' >= 1.4.0      : not found
Checking for 'eigen3' >= 3.1.2           : not found
Checking for header windows.h            : yes
Checking for 'portaudio-2.0' >= 19       : not found
Checking for header mmsystem.h           : yes
Checking for 'celt' >= 0.11.0            : not found
Checking for 'celt' >= 0.8.0             : not found
Checking for 'celt' >= 0.7.0             : not found
Checking for 'celt' >= 0.5.0             : not found
Checking for header opus/opus_custom.h   : not found
Checking for 'opus' >= 0.9.0             : yes
Checking for 'samplerate' >= 0           : not found
Checking for 'sndfile' >= 0              : not found
Checking for library readline            : not found
Checking for header readline/readline.h  : no

==================
JACK 1.9.11 svn revision will checked and eventually updated during build
Build with a maximum of 64 JACK clients
Build with a maximum of 768 ports per application
Install prefix                           :  C:/users/84110102/appdata/local/temp
Library directory                        :  C:/users/84110102/appdata/local/temp/lib
Drivers directory                        :  C:/users/84110102/appdata/local/temp/lib/jack
Build debuggable binaries                :  no
C compiler flags                         :  ['/nologo', '-Wall']
C++ compiler flags                       :  ['/nologo', '-Wall']
Linker flags                             :  ['/NOLOGO', '/MANIFEST']
Build with engine profiling              :  no
Build with 32/64 bits mixed mode         :  no
Build standard JACK (jackd)              :  yes
Build D-Bus JACK (jackdbus)              :  no
Autostart method                         :  classic
Build doxygen documentation              :  no
Enable ALSA driver                       :  no
Enable FireWire driver (FFADO)           :  no
Enable FreeBob driver                    :  no
Enable IIO driver                        :  no
Enable Portaudio driver                  :  no
Enable WinMME driver                     :  yes
Build with CELT                          :  no
Build Opus netjack2                      :  no
Build with libsamplerate                 :  no
Build with libsndfile                    :  no
Build with readline                      :  no

'configure' finished successfully (59.872s)

$ python waf build
Waf: Entering directory `D:/Test/jack-master/build'
make[1]: Entering directory `D:/Test/jack-master/build'
Traceback (most recent call last):
  **File "D:/Test/jack-master/waflib/Scripting.py", line 150, in waf_entry_point
    run_commands()
  File "D:/Test/jack-master/waflib/Scripting.py", line 252, in run_commands
    ctx = run_command(cmd_name)
  File "D:/Test/jack-master/waflib/Scripting.py", line 236, in run_command
    ctx.execute()
  File "D:/Test/jack-master/waflib/Scripting.py", line 577, in execute
    return execute_method(self)
  File "D:/Test/jack-master/waflib/Build.py", line 246, in execute
    self.execute_build()
  File "D:/Test/jack-master/waflib/Build.py", line 259, in execute_build
    self.recurse([self.run_dir])
  File "D:/Test/jack-master/waflib/Context.py", line 303, in recurse
    user_function(self)
  File "D:/Test/jack-master/wscript", line 678, in build
    bld.recurse('common')
  File "D:/Test/jack-master/waflib/Context.py", line 303, in recurse
    user_function(self)
  File "D:/Test/jack-master/common/wscript", line 338, in build
    create_jack_process_obj(bld, 'netmanager', 'JackNetManager.cpp', serverlib)
  File "D:/Test/jack-master/common/wscript", line 33, in create_jack_process_obj
    process.includes = ['.'] + env_includes + ['jack', '..']
_UnboundLocalError: local variable 'env_includes' referenced before assignment**_

**Comment by keinstein** [comment]
Hi, thanks for the report. Until today evening I can't tell whether I managed to compile this repository. My use-case is mainly RtMidi and my fork. Both do not support JACK on Windows so far.

But some remarks:
• This repository is meant to build packages for cross-building Windows applications. Installation from the command line is not intended.
• You are building using MSVC which is not available as native Linux binary.
• You should build from the official repository: https://github.com/jackaudio/jack or https://github.com/jackaudio/jack2 depending what you need and whether you prefer C or C++.

**Comment by keinstein** [comment]
I just read https://jackaudio.org/faq/build_info.html maybe `waf` would be better than `waf build`?
